# Generated by Django 2.1.5 on 2022-03-22 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idowner', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100)),
                ('file', models.CharField(max_length=100)),
                ('size', models.CharField(default='none', max_length=100)),
                ('sizeinoctet', models.IntegerField(default=0)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('guest', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='RarImages',
        ),
    ]
