# Generated by Django 2.1.5 on 2022-03-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20211103_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarimage',
            name='idowner',
            field=models.IntegerField(default=0),
        ),
    ]
