# Generated by Django 2.1.5 on 2022-03-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_rarimage_idowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarimage',
            name='size',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
