# Generated by Django 2.1.5 on 2022-03-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_rarimage_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='rarimage',
            name='sizeinoctet',
            field=models.IntegerField(default=0),
        ),
    ]
